"""API request/response models."""
from typing import Optional, List
from pydantic import BaseModel, Field


class UserProfile(BaseModel):
    """Collected by the Eligibility Profiler agent (or the frontend form)."""
    state: str = Field(..., examples=["Telangana"])
    annual_income: int = Field(..., description="Family annual income in INR", examples=[180000])
    family_size: int = Field(1, examples=[4])
    has_ration_card: bool = False
    ration_card_type: Optional[str] = Field(None, examples=["White / BPL"])
    existing_insurance: Optional[str] = Field(None, examples=["None"])
    ailment: Optional[str] = Field(None, examples=["Cardiac surgery"])
    language: str = Field("en", description="ISO code for voice guidance", examples=["te", "hi", "en"])
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class AnalyzeRequest(BaseModel):
    profile: UserProfile
    bill_text: Optional[str] = Field(
        None, description="Extracted hospital bill/estimate text (frontend or Bill parser)."
    )


class MatchedScheme(BaseModel):
    name: str
    authority: str
    coverage_amount: Optional[str] = None
    why_eligible: str


class Hospital(BaseModel):
    name: str
    address: str
    distance_note: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    phone: Optional[str] = None
    scheme_name: str = ""
    empanelment_status: str = Field(
        "verify",
        description="'confirmed' if the search was empanelment-specific and the "
        "result matched, 'verify' otherwise. Not registry-verified.",
    )
    distance_km: Optional[float] = Field(
        None, description="Haversine (straight-line) distance from the user in km."
    )


class SchemeList(BaseModel):
    """Container so CrewAI's output_pydantic (single-model) can hold a list of schemes."""
    items: List[MatchedScheme] = []


class HospitalList(BaseModel):
    """Container so CrewAI's output_pydantic (single-model) can hold a list of hospitals."""
    items: List[Hospital] = []


class DocumentChecklistOutput(BaseModel):
    checklist: List[str] = []
    draft_path: Optional[str] = None


class CoverageSummaryOutput(BaseModel):
    summary: str = ""
    bill_amount: Optional[str] = Field(
        None,
        description="Total bill amount as shown on the uploaded bill (e.g. '₹45,000'), "
        "or null if no bill was uploaded or no total could be found.",
    )
    coverage_status: str = Field(
        "unknown",
        description="One of: 'full' (scheme covers the whole bill/ailment), 'partial' "
        "(covers only part, or has caps/exclusions leaving a gap), 'none' (scheme does "
        "not cover this ailment/bill), 'unknown' (not enough information to judge, e.g. "
        "no bill uploaded).",
    )


class AnalyzeResponse(BaseModel):
    matched_schemes: List[MatchedScheme] = []
    coverage_summary: str = ""
    bill_amount: Optional[str] = None
    coverage_status: str = "unknown"
    nearby_hospitals: List[Hospital] = []
    document_checklist: List[str] = []
    voice_guidance: str = ""
    disclaimer: str = (
        "This is informational guidance generated by AI. Final eligibility and "
        "coverage must be confirmed with the official scheme portal or an "
        "empanelled hospital before relying on it."
    )
    raw_report: Optional[str] = None


class JobStatus(BaseModel):
    status: str  # "running" | "done" | "error"
    step_index: int = 0
    step_name: str = ""
    result: Optional[AnalyzeResponse] = None
    error: Optional[str] = None


class SendReportRequest(BaseModel):
    phone_number: str = Field(..., description="E.164 format, e.g. +919876543210")
    channel: str = Field(..., description="'sms' or 'whatsapp'")
    report_text: str
